### ISSUE TITLE
docker: Error response from daemon: pull access denied for seo-toolkit, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

### ISSUE THREAD

**Issue by bikker** [StanGirard/seo-audits-toolkit#11]
docker: Error response from daemon: pull access denied for seo-toolkit, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

Getting that error while doing docker run -d -p 5000:5000 seo-toolkit:latest

**Comment by StanGirard** [comment]
I have not yet published the docker image to docker.com. You first need to build it locally:
`docker build -t seo-toolkit:latest .`

**Comment by StanGirard** [comment]
I've uploaded the docker image to docker.com.
 Now you are able to pull the image with `docker pull stangirard/osat:latest` 

Closing the issue
