### ISSUE TITLE
How to get GOOGLE_API_KEY ?

### ISSUE THREAD

**Issue by lucmichalski** [StanGirard/seo-audits-toolkit#18]
Hi guys,

Hope you are all well !

Can you add to the README how to get the **GOOGLE_API_KEY** for what services ?

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by StanGirard** [comment]
Hello @lucmichalski,

Thanks for the interest for my project.

I've added in the documentation how to get your google API key.

https://developers.google.com/speed/docs/insights/v5/get-started

Best regards
