### ISSUE TITLE
error 500, KeyError: 'results' at /audit/lighthouse/score endpoint

### ISSUE THREAD

**Issue by lucmichalski** [StanGirard/seo-audits-toolkit#20]
Hi @StanGirard ,

Hope you are all well !

I managed to deploy **seo-audits-toolkit** via docker and I have some errors.

For example, /audit/lighthouse/score gives an 500 error:
<img width="1419" alt="Screenshot 2020-12-12 at 04 20 57" src="https://user-images.githubusercontent.com/1963546/101971413-7477bb80-3c31-11eb-957a-7782895e8677.png">

**Or, the serp rank or graphs are running endlessly.**

Any idea how to fix it ?

Thanks for any insights or inputs on that.

Ps. From my point of view, there is a lot of things we can add to your project and is there a way to DM you on twitter about my ideas (I speak french too). My twitter handle is https://twitter.com/lucmichalski

Cheers,
Luc Michalski

**Comment by StanGirard** [comment]
I think it is a dumb bug. Try adding the https:// before you domain name :)

**Comment by StanGirard** [comment]
And I sent you a message on twitter
