### ISSUE TITLE
Any chance to run this without an NVIDIA card/driver?

### ISSUE THREAD

**Issue by itst** [StanGirard/seo-audits-toolkit#24]
Hi Stan,

thanks for cleaning up the dependencies.

I only now realized you are using PyTorch with CUDA built in.

Any chance to run this on MacOS/without CUDA?

Thanks
Sascha

**Comment by StanGirard** [comment]
Hello,

You dont need cuda 😃 however it can be faster with it. 

I'm running it on MacBook Pro so I know it works.

**Comment by itst** [comment]
I see! Then it must be something else.

When I try to login to http://localhost:3000/#/login using admin/admin, the API gives back:

`{
    "non_field_errors": [
        "Unable to log in with provided credentials."
    ]
}`

See this screenshot for context

<img width="1147" alt="Screen Shot 2021-03-04 at 21 34 57" src="https://user-images.githubusercontent.com/177044/110026885-9022c780-7d31-11eb-8366-b7e0019ea783.png">

I am guessing this is because this step of the install process fails because it missed CUDA:

`docker exec -it osat-server python manage.py loaddata init_data.json`

Gives back:

`/opt/venv/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(django_celery_beat, solarschedule) already exists.`

` 
The above exception was the direct cause of the following exception:
[…] 
`

`django.db.utils.IntegrityError: Problem installing fixture '/opt/app/init_data.json': Could not load contenttypes.ContentType(pk=19): duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(django_celery_beat, solarschedule) already exists.`

**Comment by StanGirard** [comment]
Hello @itst, 

I managed to get your error. What I did :

`docker exec -it osat-server python manage.py flush`

Then I ran the command again: 

`docker exec -it osat-server python manage.py loaddata init_data.json`
