### ISSUE TITLE
Cannot create container for service redis

### ISSUE THREAD

**Issue by philffm** [StanGirard/seo-audits-toolkit#25]
Hi there ! I was wondering whether anyone of you encountered issues with redis?
It is the only thing that doesn't seem to work. Using the path as defined in the example.

`    volumes:
    - redis-data:/data
    - redis-logs:${REDIS_LOG_PREFIX_PATH}`

Terminal output
`Recreating osat-redis ... error

ERROR: for osat-redis  Cannot create container for service redis: failed to mount local volume: mount /Users/phil/dev/seo-audits-toolkit/shared/logs/redis:/var/lib/docker/volumes/seo-audits-toolkit_redis-logs/_data, flags: 0x1000: no such file or directory

ERROR: for redis  Cannot create container for service redis: failed to mount local volume: mount /Users/phil/dev/seo-audits-toolkit/shared/logs/redis:/var/lib/docker/volumes/seo-audits-toolkit_redis-logs/_data, flags: 0x1000: no such file or directory
ERROR: Encountered errors while bringing up the project.`

![Screenshot 2021-03-09 at 11 25 34](https://user-images.githubusercontent.com/6079545/110456698-2a846180-80ca-11eb-8a17-348275d8d66e.jpg)

Thank you very much in advance - If you have any ideas that would be great - otherwise I'll dedicate my research to Docker stuff on the weekend :D

**Comment by StanGirard** [comment]
Hello @philffm 

I think the issue is that le folder shared/logs/redis doesn't exist. Try creating it or just pull the latest version of OSAT. I've updated it to include those folders :D 

Have fun

**Comment by philffm** [comment]
Amazing, that worked 🎉
