### ISSUE TITLE
Network error, when logging in 

### ISSUE THREAD

**Issue by philffm** [StanGirard/seo-audits-toolkit#26]
Hi! I just ran into another issue,

all the containers are running but the frontend smashes a Network error, when I try to login

![Screenshot 2021-03-09 at 15 48 44](https://user-images.githubusercontent.com/6079545/110488659-f4a5a400-80ee-11eb-8612-1a47314ef071.jpg)

![Screenshot 2021-03-09 at 15 44 47](https://user-images.githubusercontent.com/6079545/110488022-6a5d4000-80ee-11eb-9c04-4ed5d55f6e60.jpg)

Do you have an idea? I checked running it with CORS disabled, same result.
![Screenshot 2021-03-09 at 15 39 39](https://user-images.githubusercontent.com/6079545/110487776-3255fd00-80ee-11eb-9cd3-c39b9ab8e687.jpg)

Thanks in advance, Phil

**Comment by Pyrrha** [comment]
Hello,

Could you provide a screen of `docker logs osat-server` and `docker logs osat-dashboard` please?

**Comment by philffm** [comment]
Ha

> There is an error that occured recently.
> 
> You should check this answer -> [#24 (comment)](https://github.com/StanGirard/seo-audits-toolkit/issues/24#issuecomment-793898511)

Ha, that fixed it 🎉 Amazing, thanks!
