### ISSUE TITLE
Serp Rank function not found in project

### ISSUE THREAD

**Issue by bijanpiri** [StanGirard/seo-audits-toolkit#30]
As mentioned in project features list it must be possible to find the rank of a website on google result page

> -  SERP Rank - Get the rank of your website on google for specific queries 

But I could not find any option in UI to do Serp rank. 

Where should I go?

**Comment by StanGirard** [comment]
Hello @bijanpiri,

The functionnalities has been removed from version 1.4 has it wasn't well implemented and could result to banning from google. 

I'm looking at another way to have it.

If you want you can get this functionality on the [Version 1.3](https://github.com/StanGirard/seo-audits-toolkit/releases/tag/V1.3) of the app
