### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/seo-audits-toolkit#6]
Please use this issue to request new features

**Comment by StanGirard** [comment]
Extensive page analysis:

- absent doctype
- absent h1 tags
-  cms
- compression disabled
- favicon invalid
- images invalid alt
- images invalid title
- links broken
- links external
- links internal
- meta description
- meta keywords
- http/https
- has flash
- has frame
- response code

Extensive website analysis
- All the above
- TBD

**Comment by SimonSchubert** [comment]
Your points above are already looking good. I personally would like to have a single page website check. Like other services do, which you find for "seo check" on google.

Here are a few more of the tests which are not already listed above:
- Deprecated HTML Tags Test
- SEO Friendly URL Test
- Sitemap Test
- Robots.txt Test
- JavaScript/CSS Minification Test
- Doctype Test
- URL Canonicalization Test (Example www.example.com, http://example.com, https://example.com, https://www.example.com should all resolve to the same url)
- HTTPS Test
- Custom 404 Error Page Test
- Structured Data Test

**Comment by StanGirard** [comment]
I'll work on the Dashboard in a bit. It is not my priority, however. 
I'd rather have a lot of features first and then create a nice dashboard for it. 

Also, I'm not a really good front-end developer 😄

**Comment by StanGirard** [comment]
@SimonSchubert  I've started working on the dashboard using Flask. New to it. If you want to take a look it is on the dashboard branch. Once it is launched just go to localhost:5000.

It is not very nice but I'm starting to get the hang of it.

<img width="1792" alt="Capture d’écran 2020-06-25 à 03 22 51" src="https://user-images.githubusercontent.com/19614572/85642972-2b3bab80-b693-11ea-85ff-7381ce340334.png">

**Comment by SimonSchubert** [comment]
So much progress, I love it! The new UI looks also great. The project earns already much more stars. After the next major release I will try to spread the word.

**Comment by StanGirard** [comment]
Thanks! A lot of work has gone into it. I've had to rethink the entire DB. Redo the architecture of the project and start working on the dashboard. 

Now that everything is a little bit cleaner and better organized I can start working on new features. 
I've started working on the website audit tool with some of the features you requested.

Should be in the next release.

**Comment by StanGirard** [comment]
Site audit is not done yet. I've started working on it -> Robot and Sitemap parser and other small things. It is, however, a bit more challenging to run all those tests. Don't know yet how to check modification.

In the meantime I have implemented a Lighthouse Audit score tracker. You can run Google Lighthouse on your website and keep the history of the scores you got. Need to implement a chart for better visualization but logic is done.

**Comment by StanGirard** [comment]
Closing Feature request. Path to V2 has been laid down. No place for new features

**Comment by 0pushpendra** [comment]
POST /audit/lighthouse/score HTTP/1.1" 302 - can you help ???  I think its a database issue ???

**Comment by StanGirard** [comment]
@0pushpendra please open an issue and explain the issue with some examples and how you got it.
